dateModified: 1580029222
email:
  fromEmail: josh@batch.nz
  fromName: 'Batch Craft Starter'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  fe6f6b78-e8c5-4738-9a49-74cc60e221dc:
    name: Common
plugins:
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
siteGroups:
  a50ebe94-de60-4d01-8ed1-cdc869db10a2:
    name: 'Batch Craft Starter'
sites:
  b64eed85-0eb2-4e61-a970-b2d6634ba3b9:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: 'Batch Craft Starter'
    primary: true
    siteGroup: a50ebe94-de60-4d01-8ed1-cdc869db10a2
    sortOrder: 1
system:
  edition: solo
  name: 'Batch Craft Starter'
  live: true
  schemaVersion: 3.3.3
  timeZone: Pacific/Fiji
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
