dateModified: 1601926179
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SENDER_NAME
  template: $HTML_EMAIL_TEMPLATE
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: ''
  transportType: craft\mailgun\MailgunAdapter
fieldGroups:
  fe6f6b78-e8c5-4738-9a49-74cc60e221dc:
    name: Common
siteGroups:
  a50ebe94-de60-4d01-8ed1-cdc869db10a2:
    name: 'Batch Craft Starter'
sites:
  b64eed85-0eb2-4e61-a970-b2d6634ba3b9:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-NZ
    name: 'Batch Craft Starter'
    primary: true
    siteGroup: a50ebe94-de60-4d01-8ed1-cdc869db10a2
    sortOrder: 1
plugins:
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    sortOrder: 1
system:
  edition: solo
  live: true
  name: 'Batch Craft Starter'
  schemaVersion: 3.5.13
  timeZone: Pacific/Auckland
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
